### ISSUE TITLE
Failed to activate the copy-paste-context package

### ISSUE THREAD

**Issue by phillipholmes** [shieldal/copy-paste-context#1]
[Enter steps to reproduce below:]
1. ... upgrade to Atom 0.187.0
2. ... launch Atom
3. ... see error message (below)

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [copy-paste-context](https://github.com/shieldal/copy-paste-context) package, v2.1.0
### Stack Trace

Failed to activate the copy-paste-context package

```
At Cannot read property 'apply' of undefined

TypeError: Cannot read property 'apply' of undefined
    at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:122:30)
    at Function.View.buildHtml (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:96:10)
    at CopyPasteContextView.View (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:121:33)
    at new CopyPasteContextView (/Users/phillip/.atom/packages/copy-paste-context/lib/copy-paste-context-view.coffee:12:57)
    at Object.module.exports.activate (/Users/phillip/.atom/packages/copy-paste-context/lib/copy-paste-context.coffee:8:42)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "welcome",
      "feedback",
      "exception-reporting",
      "autocomplete",
      "recent-projects",
      "open-last-project"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-pitchblack-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-cli-diff, v0.11.0
atom-pitchblack-syntax, v0.0.0
auto-update-packages, v0.2.2
copy-paste-context, v2.1.0
highlight-line, v0.10.1
highlight-selected, v0.9.1
minimap, v4.6.0
project-colorize, v0.1.0
remember-session, v0.5.1

# Dev
No dev packages
```

**Comment by czechbox** [comment]
Having the same issue

**Comment by brpaz** [comment]
Same issue.
